apiVersion: v1
kind: Service
metadata:
  name: rust-ceramic-lb
  annotations:
    cloud.google.com/l4-rbs: "enabled"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: rust-ceramic
  ports:
  - name: swarm-tcp
    protocol: TCP
    port: 4001
    targetPort: 4001
