---
namespace: ceramic-load-test

bases:
  - ../../base/composedb
  - ../../base/opentelemetry

resources:
  - ./manifests/runner.yaml
  - ./manifests/runner-create.yaml

images:
  - name: 3boxben/runner
    newName: 3boxben/composedb@sha256
    newTag: d404fb8c8c1c49a02002365032a315d5d0e680e2b9bb3cf776d9bd39665f3c4c
  - name: otel/opentelemetry-collector
    newName: otel/opentelemetry-collector
    newTag: 0.72.0

configMapGenerator:
  - name: schemas
    files:
      - ./schemas/SmokeTestModel-main.graphql
      - ./schemas/SmokeTestModel-relation.graphql
  - name: scripts
    files:
      - ./scripts/create-doc.sh
  - name: runner-env
    envs:
      - ./runner.env