---
namespace: ceramic-load-test

bases:
  - ../../base/composedb
  - ../../base/opentelemetry

resources:
  - ./manifests/runner.yaml
  - ./manifests/runner-create.yaml
  - ./ingress.yaml

images:
  - name: 3boxben/runner
    newName: 3boxben/composedb@sha256
    newTag: e13306b7d2e59bbb4ce228bd862a54b18b2fa047b437946e2110169fcbb32c3a
  - name: 3boxben/composedb
    newName: 3boxben/composedb@sha256
    newTag: e13306b7d2e59bbb4ce228bd862a54b18b2fa047b437946e2110169fcbb32c3a
  - name: otel/opentelemetry-collector
    newName: otel/opentelemetry-collector
    newTag: 0.72.0

configMapGenerator:
  - name: schemas
    files:
      - ./schemas/SmokeTestModel-main.graphql
      - ./schemas/SmokeTestModel-relation.graphql
  - name: scripts
    files:
      - ./scripts/create-doc.sh
  - name: runner-env
    envs:
      - ./runner.env
  - name: composedb-env
    behavior: replace
    envs:
      - ./composedb.env
  - name: composedb-init
    behavior: replace
    files:
      - ./daemon-config.json
      - ./compose-init.sh

patchesStrategicMerge:
  - ./patches/ipfs.yaml
  - ./patches/composedb.yaml