---
namespace: ceramic

resources:
  - ./manifests/ipfs.yaml
  - ./manifests/composedb.yaml
  - ./manifests/postgres.yaml

configMapGenerator:
  - name: composedb-init
    files:
      - ./daemon-config.json
      - ./compose-init.sh
  - name: composedb-env
    envs:
      - ./composedb.env

images:
  - name: 3boxben/composedb
    newName: 3boxben/composedb@sha256
    newTag: d404fb8c8c1c49a02002365032a315d5d0e680e2b9bb3cf776d9bd39665f3c4c
  - name: postgres/postgres
    newName: postgres
    newTag: 15-alpine
  - name: ipfs/ipfs
    newName: ceramicnetwork/go-ipfs-daemon@sha256
    newTag: c0c7f5886c1d86a2179cc6fba475005830ab148dde40dd7bde004fb7452bdd48