namespace: ceramic-one-mm

resources:
  - ceramic.yaml

configMapGenerator:
  - name: js-ceramic-env
    envs:
      - ./js-ceramic.env
  - name: rust-ceramic-env
    envs:
      - ./rust-ceramic.env
  - name: js-ceramic-init
    files:
      - ./daemon-config.json
      - ./js-ceramic-init.sh
