---
- hosts: all
  become: true
  roles:
    - name: ceramic-prep
      import_role:
        name: ceramic-prep
      tags: ceramic-prep
    - name: rust-ceramic
      import_role:
        name: rust-ceramic
      tags: rust-ceramic
    - name: js-ceramic
      import_role:
        name: js-ceramic
      tags: js-ceramic
