- name: Format and mount block device
  block:
    - name: Create persistant data location
      community.general.filesystem:
        fstype: ext4
        dev: "{{ ceramic_data_block_path }}"

    - name: Mount persistant data location
      ansible.posix.mount:
        path: "{{ ceramic_data_mount_path }}"
        src: "{{ ceramic_data_block_path }}"
        fstype: ext4
        state: mounted
  when: ceramic_data_block_path is defined

- name: create user
  ansible.builtin.user:
    name: ceramic
    state: present
    shell: /bin/bash
    home: /home/ceramic

- name: Create ceramic_data for persistent data storage
  ansible.builtin.file:
    path: "{{ ceramic_data_mount_path }}/ceramic_data/"
    state: directory
    owner: ceramic
  register: ceramic_data_dir

