namespace: ceramic-one-mm-prod

resources:
  - ./manifests/js-ceramic-sts.yaml
  - ./manifests/rust-ceramic-sts.yaml
  - ./manifests/rust-ceramic-lb.yaml
  - ./manifests/postgres-sts.yaml

configMapGenerator:
  - name: js-ceramic-env
    envs:
      - ./envs/js-ceramic.env
  - name: rust-ceramic-env
    envs:
      - ./envs/rust-ceramic.env
  - name: js-ceramic-init
    files:
      - ./files/daemon-config.json
      - ./files/js-ceramic-init.sh
